version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.jvm"
          - "maven.modrinth:fabric-language-kotlin"
      fabric:
        patterns:
          - "fabric-loom"
          - "net.fabricmc:fabric-loader"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
