# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: deploy
on:
  push:
    tags: ['**']

jobs:
  build:
    runs-on: ubuntu-24.04
    environment:
      name: Modrinth
      url: https://modrinth.com/mod/villager-inventory-hwyla-plugin
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: setup jdk
        uses: kphrx/setup-java@72b0832d0a6444093c42087686974c4aaca46371
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v5
      - name: version type
        uses: actions/github-script@v7
        id: version-type
        with:
          result-encoding: string
          script: |
            const version = process.env.GITHUB_REF_NAME;
            const isPrerelease = version.startsWith('0.') || version.split('-').length > 1;
            if (!isPrerelease) {
              return 'release';
            }
            if (version.startsWith('0.')) {
              return 'alpha';
            }
            const prerelease = version.split('-')[1];
            if (prerelease.split('.')[0] === 'alpha') {
              return 'alpha';
            }
            return 'beta';
      - name: build
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          VERSION_TYPE: ${{ steps.version-type.outputs.result }}
        run: ./gradlew modrinth -Prelease -Pmod_version="${GITHUB_REF_NAME}" -Pmod_version_type="${VERSION_TYPE}" -Pmodrinth_changelog="$(git tag -l --format='%(contents:subject)%0a%0a%(contents:body)' "${GITHUB_REF_NAME}")"
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
